import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/sonner";
import Sidebar from "@/components/sidebar";
import { currentUser } from "@/hooks/use-current-user-server";
import { redirect } from "next/navigation";
import { ModalProvider } from "@/provider/modal-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <ModalProvider />
          <div className="h-full w-full">{children}</div>
          <Toaster />
        </body>
      </html>
    </SessionProvider>
  );
}
