-- AlterTable
ALTER TABLE `order` ADD COLUMN `email` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `name` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `state` VARCHAR(191) NOT NULL DEFAULT '';
